#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo 'Starting dotfile bootstrap'
printf 'Bootstrap will remove current configuration files. Continue (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    echo '' 
    printf 'Removing ~/.zshrc and adding symlink to dotfiles/zsh/zshrc'
    rm -f ~/.zshrc
    rm -f ~/.p10k.zsh
    ln -s $SCRIPT_DIR/zsh/zshrc ~/.zshrc
    ln -s $SCRIPT_DIR/zsh/p10k.zsh ~/.p10k.zsh
    printf ' \xE2\x9C\x94'

    echo '' 
    printf 'Removing ~/.tmux.conf and adding symlink to dotfiles/tmux/tmux'
    rm -f ~/.tmux.conf
    ln -s $SCRIPT_DIR/tmux/tmux.conf ~/.tmux.conf
    printf ' \xE2\x9C\x94'

    echo ''
    printf 'Removing ~/.config/nvim and adding symlink to dotfiles/nvim'
    rm -rf ~/.config/nvim
    ln -s $SCRIPT_DIR/nvim ~/.config/nvim
    printf ' \xE2\x9C\x94'

    echo ''
    printf 'Removing vscode settings.json and adding symlink to dotfiles/vscode'
    rm -rf ~/Library/Application\ Support/Code/User/settings.json
    ln -s $SCRIPT_DIR/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
    printf ' \xE2\x9C\x94'

    echo ''
    printf 'Removing vscode keybindings.json and adding symlink to dotfiles/vscode'
    rm -rf ~/Library/Application\ Support/Code/User/keybindings.json
    ln -s $SCRIPT_DIR/vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json
    printf ' \xE2\x9C\x94'
    
else
    echo Aborting...
fi
echo ''
exit 0
