#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo 'Starting tmux bootstrap'
printf 'Bootstrap will remove current configuration files. Continue (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    echo ''
    printf 'Removing ~/.tmux.conf and adding symlink to this repository configuration'
    rm -f ~/.tmux.conf
    ln -s $SCRIPT_DIR/tmux.conf ~/.tmux.conf
    printf ' \xE2\x9C\x94'
else
    echo Aborting...
fi
echo ''
exit 0
