# scrollback size
set -g history-limit 99999

# Changing ctrl b to ctrl f as the command button
unbind C-b
set -g prefix C-f

# set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
set -g pane-base-index 1

# pass through xterm keys
set -g xterm-keys on

# reload tmux config with ctrl + f + r
 unbind r
 bind r \
     source-file ~/.tmux.conf \;\
         display 'Reloaded tmux config.'

# Resize panes with arrow keys
bind y resize-pane -L 10
bind u resize-pane -D 10
bind i resize-pane -U 10
bind o resize-pane -R 10

# Select panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Ctrl - w or w to kill panes
unbind e
unbind C-e
bind-key e kill-pane
bind-key C-e kill-pane

# C + control q to kill session
unbind q
unbind C-q
bind-key q kill-session
bind-key C-q kill-session

# Ctrl + f + n : New session
unbind n
unbind C-n
bind-key n new-session
bind-key C-n new-session

# Rename window to current directory
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable tmux-continuum auto load on start
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'

