#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo 'Starting zsh bootstrap'
printf 'Bootstrap will remove current configuration files. Continue (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    echo ''
    printf 'Removing ~/.zshrc and adding symlink to this repository configuration'
    rm -f ~/.zshrc
    ln -s $SCRIPT_DIR/zshrc ~/.zshrc
    printf ' \xE2\x9C\x94'
    echo ''
    printf 'Removing ~/.p10k.zsh and adding symlink to this repository configuration'
    rm -f ~/.p10k.zsh
    ln -s $SCRIPT_DIR/p10k.zsh ~/.p10k.zsh
    printf ' \xE2\x9C\x94'
else
    echo Aborting...
fi
echo ''
exit 0
